# Generated by Django 4.2.7 on 2023-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ph_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sem",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
