# Generated by Django 4.2.7 on 2023-11-21 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_course_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="course_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="app.course",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="user_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
