# Generated by Django 4.2.7 on 2023-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_registration_course_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_code",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
